In [3]:
import numpy as np
from scipy.stats import multivariate_normal

# 期待値と分散共分散行列の準備
mean = np.array([3, 5])
cov = np.array([[4, -1.2], [-1.2, 1]])

# numpy を用いた生成
data_1 = np.random.multivariate_normal(mean, cov, size=200)

# データ型の確認
print(data_1.shape)
# (200, 2)

# 期待値の確認
print(np.mean(data_1, axis=0))
# [3.00496708 4.94669956]

# 分散共分散の確認
print(np.cov(data_1, rowvar=False))
"""
[[ 3.86542859 -1.31389501]
 [-1.31389501  0.93002097]]
"""

# scipyで生成する方法
data_2 = multivariate_normal(mean, cov).rvs(size=200)
print(multivariate_normal(mean, cov))
print(multivariate_normal(mean, cov).pdf())
# データ型の確認
print(data_2.shape)
# (200, 2)

# 期待値の確認
print(np.mean(data_2, axis=0))
# [2.81459692 5.10444347]

# 分散共分散の確認
print(np.cov(data_2, rowvar=False))
"""
[[ 4.46151626 -1.28084696]
 [-1.28084696  1.06831954]]
"""

(200, 2)
[3.00348526 5.00242366]
[[ 4.04815817 -1.02221652]
 [-1.02221652  0.91061438]]
(200, 2)
[3.15020964 4.93796271]
[[ 3.92824383 -1.08416182]
 [-1.08416182  0.96414932]]


'\n[[ 4.46151626 -1.28084696]\n [-1.28084696  1.06831954]]\n'